# Generated by Django 3.0 on 2022-03-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cat',
            field=models.CharField(max_length=100),
        ),
    ]
