# Generated by Django 4.0.3 on 2022-03-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_id_alter_contact_id_alter_user_id'),
        ('myapp', '0002_auto_20220324_1618'),
    ]

    operations = [
    ]
