# Generated by Django 4.0.3 on 2022-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_20220324_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
