# Generated by Django 3.2.7 on 2022-03-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_user_img_alter_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, default='images/author-1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, default='images/author-1.jpg', null=True, upload_to='images/'),
        ),
    ]
