# Generated by Django 3.2.8 on 2022-03-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_user_img_alter_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.TextField(default='ahemdabad'),
        ),
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, default='images/author-1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, default='images/author-1.jpg', null=True, upload_to='images/'),
        ),
    ]
