# Generated by Django 4.0.3 on 2022-03-24 19:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/author-1.jpg', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[270, 200], upload_to='images/'),
        ),
    ]
