# Generated by Django 3.2.8 on 2022-03-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_book_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book',
        ),
    ]
