# Generated by Django 3.2.8 on 2022-03-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_book_book_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_sell',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
